/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        brain: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'Avenir', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '0': '0px',
        'px': '1px',
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '2.5': '0.625rem',
        '3': '0.75rem',
        '3.5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'large': '0 10px 40px -10px rgba(0, 0, 0, 0.15), 0 2px 10px -2px rgba(0, 0, 0, 0.05)',
        'glow': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.4)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      // Nuevas características de layout
      aspectRatio: {
        'video': '16 / 9',
        'square': '1 / 1',
        'portrait': '3 / 4',
        'landscape': '4 / 3',
        'ultrawide': '21 / 9',
        'golden': '1.618 / 1',
      },
      columns: {
        'xs': '16rem',
        'sm': '18rem',
        'md': '24rem',
        'lg': '32rem',
        'xl': '40rem',
        '2xl': '48rem',
        '3xl': '56rem',
        '4xl': '64rem',
        '5xl': '72rem',
        '6xl': '80rem',
        '7xl': '88rem',
      },
      // Utilidades personalizadas para layout
      gridTemplateColumns: {
        '13': 'repeat(13, minmax(0, 1fr))',
        '14': 'repeat(14, minmax(0, 1fr))',
        '15': 'repeat(15, minmax(0, 1fr))',
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      gridTemplateRows: {
        '13': 'repeat(13, minmax(0, 1fr))',
        '14': 'repeat(14, minmax(0, 1fr))',
        '15': 'repeat(15, minmax(0, 1fr))',
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      // Utilidades para break-inside
      breakInside: {
        'auto': 'auto',
        'avoid': 'avoid',
        'avoid-page': 'avoid-page',
        'avoid-column': 'avoid-column',
      },
      // Utilidades para object-fit y object-position
      objectPosition: {
        'center-top': 'center top',
        'center-bottom': 'center bottom',
        'left-top': 'left top',
        'left-center': 'left center',
        'left-bottom': 'left bottom',
        'right-top': 'right top',
        'right-center': 'right center',
        'right-bottom': 'right bottom',
      },
      // Utilidades para overflow
      overflow: {
        'clip': 'clip',
        'hidden': 'hidden',
        'visible': 'visible',
        'scroll': 'scroll',
        'auto': 'auto',
      },
      // Utilidades para z-index personalizados
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
      // Utilidades para isolation
      isolation: {
        'isolate': 'isolate',
        'auto': 'auto',
      },
      // Utilidades para visibility
      visibility: {
        'visible': 'visible',
        'hidden': 'hidden',
        'collapse': 'collapse',
      },
      // Utilidades para position
      position: {
        'static': 'static',
        'relative': 'relative',
        'absolute': 'absolute',
        'fixed': 'fixed',
        'sticky': 'sticky',
      },
      // Utilidades para display
      display: {
        'block': 'block',
        'inline-block': 'inline-block',
        'inline': 'inline',
        'flex': 'flex',
        'inline-flex': 'inline-flex',
        'grid': 'grid',
        'inline-grid': 'inline-grid',
        'table': 'table',
        'inline-table': 'inline-table',
        'table-caption': 'table-caption',
        'table-cell': 'table-cell',
        'table-column': 'table-column',
        'table-column-group': 'table-column-group',
        'table-footer-group': 'table-footer-group',
        'table-header-group': 'table-header-group',
        'table-row-group': 'table-row-group',
        'table-row': 'table-row',
        'flow-root': 'flow-root',
        'contents': 'contents',
        'list-item': 'list-item',
        'hidden': 'none',
      },
      // Utilidades para flexbox
      flexDirection: {
        'row': 'row',
        'row-reverse': 'row-reverse',
        'col': 'column',
        'col-reverse': 'column-reverse',
      },
      flexWrap: {
        'wrap': 'wrap',
        'wrap-reverse': 'wrap-reverse',
        'nowrap': 'nowrap',
      },
      flexGrow: {
        '0': '0',
        '1': '1',
      },
      flexShrink: {
        '0': '0',
        '1': '1',
      },
      flexBasis: {
        'auto': 'auto',
        '0': '0',
        'full': '100%',
      },
      // Utilidades para order
      order: {
        'first': '-9999',
        'last': '9999',
        'none': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
      },
      // Utilidades para gap
      gap: {
        '0': '0px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      // Nuevas utilidades para tipografía
      fontSmoothing: {
        'antialiased': 'antialiased',
        'subpixel-antialiased': 'subpixel-antialiased',
      },
      fontStyle: {
        'italic': 'italic',
        'not-italic': 'normal',
      },
      fontStretch: {
        'ultra-condensed': 'ultra-condensed',
        'extra-condensed': 'extra-condensed',
        'condensed': 'condensed',
        'semi-condensed': 'semi-condensed',
        'normal': 'normal',
        'semi-expanded': 'semi-expanded',
        'expanded': 'expanded',
        'extra-expanded': 'extra-expanded',
        'ultra-expanded': 'ultra-expanded',
      },
      fontVariantNumeric: {
        'normal-nums': 'normal',
        'ordinal': 'ordinal',
        'slashed-zero': 'slashed-zero',
        'lining-nums': 'lining-nums',
        'oldstyle-nums': 'oldstyle-nums',
        'proportional-nums': 'proportional-nums',
        'tabular-nums': 'tabular-nums',
        'diagonal-fractions': 'diagonal-fractions',
        'stacked-fractions': 'stacked-fractions',
      },
      letterSpacing: {
        'tighter': '-0.05em',
        'tight': '-0.025em',
        'normal': '0em',
        'wide': '0.025em',
        'wider': '0.05em',
        'widest': '0.1em',
      },
      lineClamp: {
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        'none': 'none',
      },
      lineHeight: {
        'none': '1',
        'tight': '1.25',
        'snug': '1.375',
        'normal': '1.5',
        'relaxed': '1.625',
        'loose': '2',
        '3': '.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
      },
      listStyleImage: {
        'none': 'none',
      },
      listStylePosition: {
        'inside': 'inside',
        'outside': 'outside',
      },
      listStyleType: {
        'none': 'none',
        'disc': 'disc',
        'decimal': 'decimal',
        'circle': 'circle',
        'square': 'square',
        'roman': 'upper-roman',
        'roman-lower': 'lower-roman',
        'alpha': 'upper-alpha',
        'alpha-lower': 'lower-alpha',
      },
      textAlign: {
        'left': 'left',
        'right': 'right',
        'center': 'center',
        'justify': 'justify',
        'start': 'start',
        'end': 'end',
      },
      textDecorationLine: {
        'underline': 'underline',
        'overline': 'overline',
        'line-through': 'line-through',
        'no-underline': 'none',
      },
      textDecorationColor: {
        'transparent': 'transparent',
        'current': 'currentColor',
        'primary': 'var(--color-primary)',
        'secondary': 'var(--color-secondary)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
      },
      textDecorationStyle: {
        'solid': 'solid',
        'double': 'double',
        'dotted': 'dotted',
        'dashed': 'dashed',
        'wavy': 'wavy',
      },
      textDecorationThickness: {
        'auto': 'auto',
        'from-font': 'from-font',
        '0': '0px',
        '1': '1px',
        '2': '2px',
        '4': '4px',
        '8': '8px',
      },
      textUnderlineOffset: {
        'auto': 'auto',
        '0': '0px',
        '1': '1px',
        '2': '2px',
        '4': '4px',
        '8': '8px',
      },
      textTransform: {
        'uppercase': 'uppercase',
        'lowercase': 'lowercase',
        'capitalize': 'capitalize',
        'normal-case': 'none',
      },
      textOverflow: {
        'clip': 'clip',
        'ellipsis': 'ellipsis',
      },
      textWrap: {
        'wrap': 'wrap',
        'nowrap': 'nowrap',
        'balance': 'balance',
        'pretty': 'pretty',
      },
      textIndent: {
        '0': '0px',
        '1': '0.25rem',
        '2': '0.5rem',
        '4': '1rem',
        '8': '2rem',
        '12': '3rem',
        '16': '4rem',
      },
      verticalAlign: {
        'baseline': 'baseline',
        'top': 'top',
        'middle': 'middle',
        'bottom': 'bottom',
        'text-top': 'text-top',
        'text-bottom': 'text-bottom',
        'sub': 'sub',
        'super': 'super',
      },
      whiteSpace: {
        'normal': 'normal',
        'nowrap': 'nowrap',
        'pre': 'pre',
        'pre-line': 'pre-line',
        'pre-wrap': 'pre-wrap',
        'break-spaces': 'break-spaces',
      },
      wordBreak: {
        'normal': 'normal',
        'words': 'break-words',
        'all': 'break-all',
        'keep': 'keep-all',
      },
      overflowWrap: {
        'normal': 'normal',
        'break-words': 'break-words',
        'break-all': 'break-all',
      },
      hyphens: {
        'none': 'none',
        'manual': 'manual',
        'auto': 'auto',
      },
      content: {
        'none': 'none',
      },
      // Utilidades para background
      backgroundAttachment: {
        'fixed': 'fixed',
        'local': 'local',
        'scroll': 'scroll',
      },
      backgroundClip: {
        'border': 'border-box',
        'padding': 'padding-box',
        'content': 'content-box',
        'text': 'text',
      },
      backgroundOrigin: {
        'border': 'border-box',
        'padding': 'padding-box',
        'content': 'content-box',
      },
      backgroundPosition: {
        'bottom': 'bottom',
        'center': 'center',
        'left': 'left',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        'right': 'right',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
        'top': 'top',
      },
      backgroundRepeat: {
        'repeat': 'repeat',
        'no-repeat': 'no-repeat',
        'repeat-x': 'repeat-x',
        'repeat-y': 'repeat-y',
        'repeat-round': 'round',
        'repeat-space': 'space',
      },
      backgroundSize: {
        'auto': 'auto',
        'cover': 'cover',
        'contain': 'contain',
      },
      // Nuevas utilidades para borders
      borderWidth: {
        '0': '0px',
        '1': '1px',
        '2': '2px',
        '4': '4px',
        '8': '8px',
        't-0': '0px',
        'r-0': '0px',
        'b-0': '0px',
        'l-0': '0px',
        't-1': '1px',
        'r-1': '1px',
        'b-1': '1px',
        'l-1': '1px',
        't-2': '2px',
        'r-2': '2px',
        'b-2': '2px',
        'l-2': '2px',
        't-4': '4px',
        'r-4': '4px',
        'b-4': '4px',
        'l-4': '4px',
        't-8': '8px',
        'r-8': '8px',
        'b-8': '8px',
        'l-8': '8px',
      },
      borderColor: {
        'transparent': 'transparent',
        'current': 'currentColor',
        'primary': 'var(--color-primary)',
        'secondary': 'var(--color-secondary)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
        'brain': 'var(--color-brain)',
      },
      borderStyle: {
        'solid': 'solid',
        'dashed': 'dashed',
        'dotted': 'dotted',
        'double': 'double',
        'hidden': 'hidden',
        'none': 'none',
      },
      // Utilidades para outline
      outlineWidth: {
        '0': '0px',
        '1': '1px',
        '2': '2px',
        '4': '4px',
        '8': '8px',
      },
      outlineColor: {
        'transparent': 'transparent',
        'current': 'currentColor',
        'primary': 'var(--color-primary)',
        'secondary': 'var(--color-secondary)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
        'brain': 'var(--color-brain)',
      },
      outlineStyle: {
        'solid': 'solid',
        'dashed': 'dashed',
        'dotted': 'dotted',
        'double': 'double',
        'hidden': 'hidden',
        'none': 'none',
        'auto': 'auto',
      },
      outlineOffset: {
        '0': '0px',
        '1': '1px',
        '2': '2px',
        '4': '4px',
        '8': '8px',
      },
      // Utilidades para box-shadow extendidas
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'large': '0 10px 40px -10px rgba(0, 0, 0, 0.15), 0 2px 10px -2px rgba(0, 0, 0, 0.05)',
        'glow': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.4)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'none': 'none',
        'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'md': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'colored': '0 20px 25px -5px rgba(59, 130, 246, 0.1), 0 10px 10px -5px rgba(59, 130, 246, 0.04)',
        'glow-primary': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-success': '0 0 20px rgba(34, 197, 94, 0.3)',
        'glow-warning': '0 0 20px rgba(245, 158, 11, 0.3)',
        'glow-error': '0 0 20px rgba(239, 68, 68, 0.3)',
        'glow-brain': '0 0 20px rgba(14, 165, 233, 0.3)',
      },
      // Utilidades para text-shadow
      textShadow: {
        'none': 'none',
        'sm': '0 1px 2px rgba(0, 0, 0, 0.1)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.1)',
        'xl': '0 8px 16px rgba(0, 0, 0, 0.1)',
        'glow': '0 0 10px rgba(59, 130, 246, 0.5)',
        'glow-lg': '0 0 20px rgba(59, 130, 246, 0.7)',
        'colored': '0 2px 4px rgba(59, 130, 246, 0.3)',
      },
      // Utilidades para opacity
      opacity: {
        '0': '0',
        '5': '0.05',
        '10': '0.1',
        '20': '0.2',
        '25': '0.25',
        '30': '0.3',
        '40': '0.4',
        '50': '0.5',
        '60': '0.6',
        '70': '0.7',
        '75': '0.75',
        '80': '0.8',
        '90': '0.9',
        '95': '0.95',
        '100': '1',
      },
      // Utilidades para blend modes
      mixBlendMode: {
        'normal': 'normal',
        'multiply': 'multiply',
        'screen': 'screen',
        'overlay': 'overlay',
        'darken': 'darken',
        'lighten': 'lighten',
        'color-dodge': 'color-dodge',
        'color-burn': 'color-burn',
        'hard-light': 'hard-light',
        'soft-light': 'soft-light',
        'difference': 'difference',
        'exclusion': 'exclusion',
        'hue': 'hue',
        'saturation': 'saturation',
        'color': 'color',
        'luminosity': 'luminosity',
      },
      backgroundBlendMode: {
        'normal': 'normal',
        'multiply': 'multiply',
        'screen': 'screen',
        'overlay': 'overlay',
        'darken': 'darken',
        'lighten': 'lighten',
        'color-dodge': 'color-dodge',
        'color-burn': 'color-burn',
        'hard-light': 'hard-light',
        'soft-light': 'soft-light',
        'difference': 'difference',
        'exclusion': 'exclusion',
        'hue': 'hue',
        'saturation': 'saturation',
        'color': 'color',
        'luminosity': 'luminosity',
      },
      // Utilidades para mask
      maskClip: {
        'border': 'border-box',
        'padding': 'padding-box',
        'content': 'content-box',
        'text': 'text',
        'no-clip': 'no-clip',
      },
      maskComposite: {
        'add': 'add',
        'subtract': 'subtract',
        'intersect': 'intersect',
        'exclude': 'exclude',
      },
      maskImage: {
        'none': 'none',
        'gradient': 'linear-gradient(to right, transparent, black)',
        'radial': 'radial-gradient(circle, transparent 0%, black 100%)',
      },
      maskMode: {
        'alpha': 'alpha',
        'luminance': 'luminance',
        'match-source': 'match-source',
      },
      maskOrigin: {
        'border': 'border-box',
        'padding': 'padding-box',
        'content': 'content-box',
        'margin': 'margin-box',
        'fill': 'fill-box',
        'stroke': 'stroke-box',
        'view-box': 'view-box',
      },
      maskPosition: {
        'center': 'center',
        'top': 'top',
        'right': 'right',
        'bottom': 'bottom',
        'left': 'left',
        'left-top': 'left top',
        'right-top': 'right top',
        'bottom-left': 'bottom left',
        'bottom-right': 'bottom right',
      },
      maskRepeat: {
        'repeat': 'repeat',
        'no-repeat': 'no-repeat',
        'repeat-x': 'repeat-x',
        'repeat-y': 'repeat-y',
        'round': 'round',
        'space': 'space',
      },
      maskSize: {
        'auto': 'auto',
        'cover': 'cover',
        'contain': 'contain',
        'max': 'max',
        'min': 'min',
      },
      maskType: {
        'alpha': 'alpha',
        'luminance': 'luminance',
      },
      // Utilidades para filters
      filter: {
        'none': 'none',
        'blur': 'blur(4px)',
        'blur-sm': 'blur(2px)',
        'blur-md': 'blur(8px)',
        'blur-lg': 'blur(12px)',
        'blur-xl': 'blur(16px)',
        'blur-2xl': 'blur(24px)',
        'blur-3xl': 'blur(40px)',
        'brightness-0': 'brightness(0)',
        'brightness-50': 'brightness(.5)',
        'brightness-75': 'brightness(.75)',
        'brightness-90': 'brightness(.9)',
        'brightness-95': 'brightness(.95)',
        'brightness-100': 'brightness(1)',
        'brightness-105': 'brightness(1.05)',
        'brightness-110': 'brightness(1.1)',
        'brightness-125': 'brightness(1.25)',
        'brightness-150': 'brightness(1.5)',
        'brightness-200': 'brightness(2)',
        'contrast-0': 'contrast(0)',
        'contrast-50': 'contrast(.5)',
        'contrast-75': 'contrast(.75)',
        'contrast-100': 'contrast(1)',
        'contrast-125': 'contrast(1.25)',
        'contrast-150': 'contrast(1.5)',
        'contrast-200': 'contrast(2)',
        'drop-shadow': 'drop-shadow(0 1px 2px rgb(0 0 0 / 0.1)) drop-shadow(0 1px 1px rgb(0 0 0 / 0.06))',
        'drop-shadow-sm': 'drop-shadow(0 1px 1px rgb(0 0 0 / 0.05))',
        'drop-shadow-md': 'drop-shadow(0 4px 3px rgb(0 0 0 / 0.07)) drop-shadow(0 2px 2px rgb(0 0 0 / 0.06))',
        'drop-shadow-lg': 'drop-shadow(0 10px 8px rgb(0 0 0 / 0.04)) drop-shadow(0 4px 3px rgb(0 0 0 / 0.1))',
        'drop-shadow-xl': 'drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08))',
        'drop-shadow-2xl': 'drop-shadow(0 25px 25px rgb(0 0 0 / 0.15))',
        'drop-shadow-none': 'drop-shadow(0 0 #0000)',
        'grayscale': 'grayscale(100%)',
        'grayscale-0': 'grayscale(0)',
        'hue-rotate-0': 'hue-rotate(0deg)',
        'hue-rotate-15': 'hue-rotate(15deg)',
        'hue-rotate-30': 'hue-rotate(30deg)',
        'hue-rotate-60': 'hue-rotate(60deg)',
        'hue-rotate-90': 'hue-rotate(90deg)',
        'hue-rotate-180': 'hue-rotate(180deg)',
        'invert': 'invert(100%)',
        'invert-0': 'invert(0)',
        'saturate-0': 'saturate(0)',
        'saturate-50': 'saturate(.5)',
        'saturate-100': 'saturate(1)',
        'saturate-150': 'saturate(1.5)',
        'saturate-200': 'saturate(2)',
        'sepia': 'sepia(100%)',
        'sepia-0': 'sepia(0)',
      },
      // Utilidades para backdrop filters
      backdropFilter: {
        'none': 'none',
        'blur': 'blur(4px)',
        'blur-sm': 'blur(2px)',
        'blur-md': 'blur(8px)',
        'blur-lg': 'blur(12px)',
        'blur-xl': 'blur(16px)',
        'blur-2xl': 'blur(24px)',
        'blur-3xl': 'blur(40px)',
        'brightness-0': 'brightness(0)',
        'brightness-50': 'brightness(.5)',
        'brightness-75': 'brightness(.75)',
        'brightness-90': 'brightness(.9)',
        'brightness-95': 'brightness(.95)',
        'brightness-100': 'brightness(1)',
        'brightness-105': 'brightness(1.05)',
        'brightness-110': 'brightness(1.1)',
        'brightness-125': 'brightness(1.25)',
        'brightness-150': 'brightness(1.5)',
        'brightness-200': 'brightness(2)',
        'contrast-0': 'contrast(0)',
        'contrast-50': 'contrast(.5)',
        'contrast-75': 'contrast(.75)',
        'contrast-100': 'contrast(1)',
        'contrast-125': 'contrast(1.25)',
        'contrast-150': 'contrast(1.5)',
        'contrast-200': 'contrast(2)',
        'grayscale': 'grayscale(100%)',
        'grayscale-0': 'grayscale(0)',
        'hue-rotate-0': 'hue-rotate(0deg)',
        'hue-rotate-15': 'hue-rotate(15deg)',
        'hue-rotate-30': 'hue-rotate(30deg)',
        'hue-rotate-60': 'hue-rotate(60deg)',
        'hue-rotate-90': 'hue-rotate(90deg)',
        'hue-rotate-180': 'hue-rotate(180deg)',
        'invert': 'invert(100%)',
        'invert-0': 'invert(0)',
        'opacity-0': 'opacity(0)',
        'opacity-5': 'opacity(.05)',
        'opacity-10': 'opacity(.1)',
        'opacity-20': 'opacity(.2)',
        'opacity-25': 'opacity(.25)',
        'opacity-30': 'opacity(.3)',
        'opacity-40': 'opacity(.4)',
        'opacity-50': 'opacity(.5)',
        'opacity-60': 'opacity(.6)',
        'opacity-70': 'opacity(.7)',
        'opacity-75': 'opacity(.75)',
        'opacity-80': 'opacity(.8)',
        'opacity-90': 'opacity(.9)',
        'opacity-95': 'opacity(.95)',
        'opacity-100': 'opacity(1)',
        'saturate-0': 'saturate(0)',
        'saturate-50': 'saturate(.5)',
        'saturate-100': 'saturate(1)',
        'saturate-150': 'saturate(1.5)',
        'saturate-200': 'saturate(2)',
        'sepia': 'sepia(100%)',
        'sepia-0': 'sepia(0)',
      },
      // Utilidades para tables
      borderCollapse: {
        'collapse': 'collapse',
        'separate': 'separate',
      },
      borderSpacing: {
        '0': '0px',
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '2.5': '0.625rem',
        '3': '0.75rem',
        '3.5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      tableLayout: {
        'auto': 'auto',
        'fixed': 'fixed',
      },
      captionSide: {
        'top': 'top',
        'bottom': 'bottom',
      },
      // Utilidades para transitions
      transitionProperty: {
        'none': 'none',
        'all': 'all',
        'colors': 'color, background-color, border-color, text-decoration-color, fill, stroke',
        'opacity': 'opacity',
        'shadow': 'box-shadow',
        'transform': 'transform',
      },
      transitionDuration: {
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      transitionTimingFunction: {
        'linear': 'linear',
        'in': 'cubic-bezier(0.4, 0, 1, 1)',
        'out': 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDelay: {
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      // Utilidades para animation
      animation: {
        'none': 'none',
        'spin': 'spin 1s linear infinite',
        'ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce': 'bounce 1s infinite',
        'fade-in': 'fade-in 0.5s ease-in-out',
        'slide-up': 'slide-up 0.5s ease-out',
        'slide-down': 'slide-down 0.5s ease-out',
        'scale-in': 'scale-in 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      // Utilidades para transforms
      backfaceVisibility: {
        'visible': 'visible',
        'hidden': 'hidden',
      },
      perspective: {
        'none': 'none',
        '250': '250px',
        '500': '500px',
        '750': '750px',
        '1000': '1000px',
      },
      perspectiveOrigin: {
        'center': 'center',
        'top': 'top',
        'top-right': 'top right',
        'right': 'right',
        'bottom-right': 'bottom right',
        'bottom': 'bottom',
        'bottom-left': 'bottom left',
        'left': 'left',
        'top-left': 'top left',
      },
      rotate: {
        '0': '0deg',
        '1': '1deg',
        '2': '2deg',
        '3': '3deg',
        '6': '6deg',
        '12': '12deg',
        '45': '45deg',
        '90': '90deg',
        '180': '180deg',
      },
      scale: {
        '0': '0',
        '50': '.5',
        '75': '.75',
        '90': '.9',
        '95': '.95',
        '100': '1',
        '105': '1.05',
        '110': '1.1',
        '125': '1.25',
        '150': '1.5',
      },
      skew: {
        '0': '0deg',
        '1': '1deg',
        '2': '2deg',
        '3': '3deg',
        '6': '6deg',
        '12': '12deg',
      },
      transformOrigin: {
        'center': 'center',
        'top': 'top',
        'top-right': 'top right',
        'right': 'right',
        'bottom-right': 'bottom right',
        'bottom': 'bottom',
        'bottom-left': 'bottom left',
        'left': 'left',
        'top-left': 'top left',
      },
      transformStyle: {
        'flat': 'flat',
        'preserve-3d': 'preserve-3d',
      },
      translate: {
        '0': '0px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
        'full': '100%',
      },
      // Utilidades para interactividad
      accentColor: {
        'auto': 'auto',
        'primary': 'hsl(var(--color-primary-500))',
        'secondary': 'hsl(var(--color-secondary-500))',
        'success': 'hsl(var(--color-success-500))',
        'warning': 'hsl(var(--color-warning-500))',
        'error': 'hsl(var(--color-error-500))',
      },
      appearance: {
        'none': 'none',
        'auto': 'auto',
      },
      caretColor: {
        'auto': 'auto',
        'transparent': 'transparent',
        'current': 'currentColor',
        'primary': 'hsl(var(--color-primary-500))',
        'secondary': 'hsl(var(--color-secondary-500))',
        'success': 'hsl(var(--color-success-500))',
        'warning': 'hsl(var(--color-warning-500))',
        'error': 'hsl(var(--color-error-500))',
      },
      colorScheme: {
        'light': 'light',
        'dark': 'dark',
        'only': 'only',
      },
      cursor: {
        'auto': 'auto',
        'default': 'default',
        'pointer': 'pointer',
        'wait': 'wait',
        'text': 'text',
        'move': 'move',
        'help': 'help',
        'not-allowed': 'not-allowed',
        'progress': 'progress',
        'crosshair': 'crosshair',
        'vertical-text': 'vertical-text',
        'alias': 'alias',
        'copy': 'copy',
        'no-drop': 'no-drop',
        'grab': 'grab',
        'grabbing': 'grabbing',
        'all-scroll': 'all-scroll',
        'col-resize': 'col-resize',
        'row-resize': 'row-resize',
        'n-resize': 'n-resize',
        'e-resize': 'e-resize',
        's-resize': 's-resize',
        'w-resize': 'w-resize',
        'ne-resize': 'ne-resize',
        'nw-resize': 'nw-resize',
        'se-resize': 'se-resize',
        'sw-resize': 'sw-resize',
        'ew-resize': 'ew-resize',
        'ns-resize': 'ns-resize',
        'nesw-resize': 'nesw-resize',
        'nwse-resize': 'nwse-resize',
        'zoom-in': 'zoom-in',
        'zoom-out': 'zoom-out',
      },
      fieldSizing: {
        'auto': 'auto',
        'content': 'content',
        'min': 'min',
        'max': 'max',
        'fit-content': 'fit-content',
      },
      pointerEvents: {
        'none': 'none',
        'auto': 'auto',
        'fill': 'fill',
        'stroke': 'stroke',
        'painted': 'painted',
        'visible': 'visible',
        'visible-fill': 'visible-fill',
        'visible-stroke': 'visible-stroke',
        'visible-painted': 'visible-painted',
        'bounding-box': 'bounding-box',
        'all': 'all',
      },
      resize: {
        'none': 'none',
        'y': 'vertical',
        'x': 'horizontal',
        'both': 'both',
      },
      scrollBehavior: {
        'auto': 'auto',
        'smooth': 'smooth',
      },
      scrollMargin: {
        '0': '0px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      scrollPadding: {
        '0': '0px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      scrollSnapAlign: {
        'start': 'start',
        'end': 'end',
        'center': 'center',
        'align-none': 'none',
      },
      scrollSnapStop: {
        'normal': 'normal',
        'always': 'always',
      },
      scrollSnapType: {
        'none': 'none',
        'x': 'x',
        'y': 'y',
        'both': 'both',
        'mandatory': 'mandatory',
        'proximity': 'proximity',
      },
      touchAction: {
        'auto': 'auto',
        'none': 'none',
        'pan-x': 'pan-x',
        'pan-left': 'pan-left',
        'pan-right': 'pan-right',
        'pan-y': 'pan-y',
        'pan-up': 'pan-up',
        'pan-down': 'pan-down',
        'pinch-zoom': 'pinch-zoom',
        'manipulation': 'manipulation',
      },
      userSelect: {
        'none': 'none',
        'text': 'text',
        'all': 'all',
        'auto': 'auto',
        'contain': 'contain',
      },
      willChange: {
        'auto': 'auto',
        'scroll-position': 'scroll-position',
        'contents': 'contents',
        'transform': 'transform',
        'opacity': 'opacity',
        'top': 'top',
        'left': 'left',
        'right': 'right',
        'bottom': 'bottom',
      },
      // Utilidades para SVG
      fill: {
        'none': 'none',
        'current': 'currentColor',
        'primary': 'hsl(var(--color-primary-500))',
        'secondary': 'hsl(var(--color-secondary-500))',
        'success': 'hsl(var(--color-success-500))',
        'warning': 'hsl(var(--color-warning-500))',
        'error': 'hsl(var(--color-error-500))',
      },
      stroke: {
        'none': 'none',
        'current': 'currentColor',
        'primary': 'hsl(var(--color-primary-500))',
        'secondary': 'hsl(var(--color-secondary-500))',
        'success': 'hsl(var(--color-success-500))',
        'warning': 'hsl(var(--color-warning-500))',
        'error': 'hsl(var(--color-error-500))',
      },
      strokeWidth: {
        '0': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
        '13': '13',
        '14': '14',
        '15': '15',
        '16': '16',
      },
      // Utilidades para accesibilidad
      forcedColorAdjust: {
        'auto': 'auto',
        'none': 'none',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
} 